### ISSUE TITLE
Docker exec does not work

### ISSUE THREAD

**Issue by qqpann** [minerllabs/basalt_2022_competition_submission_template#1]
I tried to run the code inside docker, but it doesn't work.

```sh
docker build -t qpan/minerl .  
docker run --rm -it -d --name minerl qpan/minerl
docker exec -it minerl /bin/bash 
# inside docker
python run.py
```

Run the above code and I get the error below.
Could anyone help?

<details>

```sh
(minerl) aicrowd@b0e7db2c45ae:~$ python run.py 
2022-08-25 14:36:21 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] INFO Starting Minecraft process: ['/home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/minerl/env/../MCP-Reborn/launchClient.sh', '-port', '11364', '-env', '-runDir', '/home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/minerl/env/../MCP-Reborn/run']
2022-08-25 14:36:21 b0e7db2c45ae process_watcher[139] INFO Launching process watcher daemonizer.
/home/aicrowd/.conda/envs/minerl/lib/python3.7/runpy.py:125: RuntimeWarning: 'minerl.utils.process_watcher' found in sys.modules after import of package 'minerl.utils', but prior to execution of 'minerl.utils.process_watcher'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
2022-08-25 14:36:22 b0e7db2c45ae process_watcher[139] INFO Process watcher daemonizer launched successfully.
2022-08-25 14:36:22 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG /home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/minerl/env/../MCP-Reborn
2022-08-25 14:36:30 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2022-08-25 14:36:30 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG SLF4J: Defaulting to no-operation (NOP) logger implementation
2022-08-25 14:36:30 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022-08-25 14:36:32 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG [14:36:32] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR [14:36:33] [Render thread/ERROR]: Failed to verify authentication!
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG [14:36:33] [Render thread/INFO]: Setting user: Player314
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG [14:36:33] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 SNAPSHOT
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG ---- Minecraft Crash Report ----
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG // Why is it breaking :(
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG 
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG Time: 8/25/22 2:36 PM
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG Description: Initializing game
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG 
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR java.lang.IllegalStateException: Failed to initialize GLFW, errors: GLFW error during init: [0x10008]140030032105152
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG 	at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:80)
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG 	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:586)
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:406)
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG 	at net.minecraft.client.main.Main.main(Main.java:154)
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG 
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG 
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG A detailed walkthrough of the error, its code path and all known details is as follows:
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG ---------------------------------------------------------------------------------------
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG 
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG -- Head --
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG Thread: Render thread
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG Stacktrace:
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG 	at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:80)
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG 	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:586)
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:406)
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG 
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG -- Initialization --
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG Details:
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG Stacktrace:
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG 	at net.minecraft.client.main.Main.main(Main.java:154)
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG 
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG -- System Details --
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG Details:
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG 	Minecraft Version: 1.16.5
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG 	Minecraft Version ID: 1.16.5
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG 	Operating System: Linux (amd64) version 5.15.0-46-generic
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG 	Java Version: 1.8.0_342, Private Build
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG 	Memory: 810287096 bytes (772 MB) / 1138229248 bytes (1085 MB) up to 3817865216 bytes (3641 MB)
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG 	CPUs: 12
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG 	JVM Flags: 1 total; -Xmx4G
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG 	Launched Version: ~~NULL~~
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG 	Backend library: LWJGL version 3.2.2 SNAPSHOT
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG 	Backend API: NO CONTEXT
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG 	GL Caps: 
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG 	Using VBOs: Yes
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG 	Is Modded: Very likely; Jar signature invalidated
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG 	Type: Client (map_client.txt)
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG 	CPU: <unknown>
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] DEBUG #@!@# Game crashed! Crash report saved to: #@!@# /home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/minerl/MCP-Reborn/./crash-reports/crash-2022-08-25_14.36.33-client.txt
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR /home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/minerl/env/../MCP-Reborn
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR SLF4J: Defaulting to no-operation (NOP) logger implementation
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR [14:36:32] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR [14:36:33] [Render thread/ERROR]: Failed to verify authentication!
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR [14:36:33] [Render thread/INFO]: Setting user: Player314
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR [14:36:33] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 SNAPSHOT
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR ---- Minecraft Crash Report ----
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR // Why is it breaking :(
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR 
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR Time: 8/25/22 2:36 PM
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR Description: Initializing game
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR 
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR java.lang.IllegalStateException: Failed to initialize GLFW, errors: GLFW error during init: [0x10008]140030032105152
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR 	at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:80)
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR 	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:586)
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:406)
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR 	at net.minecraft.client.main.Main.main(Main.java:154)
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR 
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR 
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR A detailed walkthrough of the error, its code path and all known details is as follows:
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR ---------------------------------------------------------------------------------------
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR 
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR -- Head --
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR Thread: Render thread
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR Stacktrace:
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR 	at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:80)
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR 	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:586)
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:406)
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR 
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR -- Initialization --
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR Details:
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR Stacktrace:
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR 	at net.minecraft.client.main.Main.main(Main.java:154)
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR 
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR -- System Details --
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR Details:
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR 	Minecraft Version: 1.16.5
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR 	Minecraft Version ID: 1.16.5
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR 	Operating System: Linux (amd64) version 5.15.0-46-generic
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR 	Java Version: 1.8.0_342, Private Build
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR 	Memory: 810287096 bytes (772 MB) / 1138229248 bytes (1085 MB) up to 3817865216 bytes (3641 MB)
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR 	CPUs: 12
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR 	JVM Flags: 1 total; -Xmx4G
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR 	Launched Version: ~~NULL~~
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR 	Backend library: LWJGL version 3.2.2 SNAPSHOT
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR 	Backend API: NO CONTEXT
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR 	GL Caps: 
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR 	Using VBOs: Yes
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR 	Is Modded: Very likely; Jar signature invalidated
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR 	Type: Client (map_client.txt)
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR 	CPU: <unknown>
2022-08-25 14:36:33 b0e7db2c45ae minerl.env.malmo.instance.76ab63[139] ERROR #@!@# Game crashed! Crash report saved to: #@!@# /home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/minerl/MCP-Reborn/./crash-reports/crash-2022-08-25_14.36.33-client.txt
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    test_BuildVillageHouse.main()
  File "/home/aicrowd/test_BuildVillageHouse.py", line 24, in main
    obs = env.reset()
  File "/home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/gym/wrappers/time_limit.py", line 27, in reset
    return self.env.reset(**kwargs)
  File "/home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/minerl/herobraine/env_specs/basalt_specs.py", line 78, in reset
    return self.env.reset()
  File "/home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/minerl/herobraine/env_specs/basalt_specs.py", line 57, in reset
    return super().reset()
  File "/home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/gym/core.py", line 251, in reset
    return self.env.reset(**kwargs)
  File "/home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/minerl/env/_singleagent.py", line 22, in reset
    multi_obs = super().reset()
  File "/home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/minerl/env/_multiagent.py", line 436, in reset
    self._setup_instances()
  File "/home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/minerl/env/_multiagent.py", line 539, in _setup_instances
    self.instances.extend([f.result() for f in instance_futures])
  File "/home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/minerl/env/_multiagent.py", line 539, in <listcomp>
    self.instances.extend([f.result() for f in instance_futures])
  File "/home/aicrowd/.conda/envs/minerl/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/home/aicrowd/.conda/envs/minerl/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/aicrowd/.conda/envs/minerl/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/minerl/env/_multiagent.py", line 805, in _get_new_instance
    instance.launch(replaceable=self._is_fault_tolerant)
  File "/home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/minerl/env/malmo.py", line 428, in launch
    error_str + "\n\nMinecraft process finished unexpectedly. There was an error with Malmo.")
EOFError: /home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/minerl/env/../MCP-Reborn
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[14:36:32] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:36:33] [Render thread/ERROR]: Failed to verify authentication!
[14:36:33] [Render thread/INFO]: Setting user: Player314
[14:36:33] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 SNAPSHOT
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 8/25/22 2:36 PM
Description: Initializing game

java.lang.IllegalStateException: Failed to initialize GLFW, errors: GLFW error during init: [0x10008]140030032105152
	at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:80)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:586)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:406)
	at net.minecraft.client.main.Main.main(Main.java:154)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:80)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:586)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:406)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:154)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 5.15.0-46-generic
	Java Version: 1.8.0_342, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 810287096 bytes (772 MB) / 1138229248 bytes (1085 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 12
	JVM Flags: 1 total; -Xmx4G
	Launched Version: ~~NULL~~
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/minerl/MCP-Reborn/./crash-reports/crash-2022-08-25_14.36.33-client.txt


Minecraft process finished unexpectedly. There was an error with Malmo.
(minerl) aicrowd@b0e7db2c45ae:~$ exit
aicrowd@b0e7db2c45ae:~$ exit

```

</details>

**Comment by qqpann** [comment]
Error log:

<details>

```txt
(base) aicrowd@b0e7db2c45ae:~$ cat /home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/minerl/MCP-Reborn/./crash-reports/crash-2022-08-25_14.36.33-client.txt
---- Minecraft Crash Report ----
// You're mean.

Time: 8/25/22 2:36 PM
Description: Initializing game

java.lang.IllegalStateException: Failed to initialize GLFW, errors: GLFW error during init: [0x10008]140030032105152
	at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:80)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:586)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:406)
	at net.minecraft.client.main.Main.main(Main.java:154)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:80)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:586)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:406)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:154)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 5.15.0-46-generic
	Java Version: 1.8.0_342, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 810287096 bytes (772 MB) / 1138229248 bytes (1085 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 12
	JVM Flags: 1 total; -Xmx4G
	Launched Version: ~~NULL~~
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	CPU: <unknown>(base)
```

</details>

**Comment by qqpann** [comment]
![gitlab aicrowd com_qiushi_basalt_2022_competition_submission_template_-_issues_2](https://user-images.githubusercontent.com/17402261/186699549-c21cc5cb-908b-4339-89fc-04595bc2a3c2.png)

Also, cloning and submitting the template code out of the box doesn't work.
I did not change anything and it fails to submit.

**Comment by qqpann** [comment]
@Miffyli @skbly7 @KarolisRam @brandonhoughton Could you help me with this?
I cannot get out of the environmental issue and cannot get into the competition at all.

**Comment by Miffyli** [comment]
Hey. Check out the new changes to the repository (merged yesterday). There were some typos in the code which made the debug submission fail with this template.
